### ISSUE TITLE
Could talos be implemented with Ollama + LLM model?

### ISSUE THREAD

**Issue by cachatj** [spyglass-search/talos#8]
Really interested to check this out & install locally, but concerned about Mimex I suppose. From what it seems like, Mimex is a storage & retrieval component right? The embedding/vector store that holds short term memory basically? 

That’s different & distinct from the local model itself, right? So in terms of local LLM model choice - is having an api endpoint the main requirement? Talos doesn’t care which model or how it’s hosted, just that there is an api endpoint it can hit?? 

Would be setting up on a MBP M2 with Llama2 setup via Ollama. Any words of wisedom??

**Comment by a5huynh** [comment]
hey @cachatj, 

Outside of the memory store, `memex` provides functionality we use inside talos (such as breaking down large files/content when doing summarization). So it's more than just an API to call out to an LLM, it does require that service to have the right functionality to do any of the complex features inside talos. 

That being said, `memex` just needs you to point to your local model so if you know to get things running w/ ollama you can do it with `memex` as well. I've tested it locally w/ a MBP M2 & the Mistral 7B model.

Let me know if that answers your question!
